<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>false</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>OMSI.NavBR.Multiplayer.WinUI</AssemblyName>
    <RootNamespace>NavBR.Client.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\NavBR.Client\Assets\NavBR.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1" />
  </ItemGroup>

  <Target Name="AddProjectPriToResolvedFileToPublish"
          BeforeTargets="ComputeResolvedFilesToPublishList"
          DependsOnTargets="$(GenerateProjectPriFile)">
    <ItemGroup>
      <ResolvedFileToPublish Include="$(ProjectPriFullPath)"
                             Condition="Exists('$(ProjectPriFullPath)')">
        <RelativePath>$(ProjectPriFileName)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
