<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <VersionPrefix>0.3.0</VersionPrefix>
    <VersionSuffix>alpha.6</VersionSuffix>
    <Product>OMSI NavBR Multiplayer</Product>
    <Company>NavBR</Company>
    <Authors>MichaelPriest</Authors>
  </PropertyGroup>
</Project>
