FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore src/NavBR.Server/NavBR.Server.csproj
RUN dotnet publish src/NavBR.Server/NavBR.Server.csproj \
    -c Release \
    --no-restore \
    -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_EnableDiagnostics=0

COPY --from=build /app/publish .

EXPOSE 10000

ENTRYPOINT ["dotnet", "NavBR.Server.dll"]
