const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
const fmtBytes=n=>{n=Number(n)||0;if(!n)return'';if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';if(n<1073741824)return(n/1048576).toFixed(1)+' MB';return(n/1073741824).toFixed(2)+' GB'};
const fmtDate=v=>{try{return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v))}catch{return''}};
const alphaKey=t=>{const m=String(t||'').match(/alpha\.(\d+)/i);return m?'alpha.'+m[1]:null};
const alphaNum=k=>Number(String(k||'').match(/(\d+)/)?.[1]||-1);
const assetLabel=n=>/standalone.*\.exe$/i.test(n)?'EXE standalone':/plugin/i.test(n)?'Plugin OMSI':/server/i.test(n)?'Servidor':/simulator/i.test(n)?'Simulador':/\.zip$/i.test(n)?'Pacote ZIP':'Download';
let releases=[],query='',filter='all';
function assetCard(a,i){return '<article class="release-card">'+
  '<div class="meta"><span class="tag">'+(i===0?'RECOMENDADO':assetLabel(a.name))+'</span><small>'+fmtBytes(a.size)+'</small></div>'+
  '<h3>'+assetLabel(a.name)+'</h3><p>'+a.name+'</p><div class="downloads">'+fmt(a.download_count)+' downloads</div>'+
  '<div class="asset-list"><a href="'+a.browser_download_url+'" target="_blank" rel="noreferrer"><span><b>Baixar</b><small>'+fmtBytes(a.size)+'</small></span><strong>→</strong></a></div></article>'}
function releaseCard(r){const assets=(r.assets||[]).filter(a=>/\.(exe|zip)$/i.test(a.name||''));const count=assets.reduce((s,a)=>s+(Number(a.download_count)||0),0);return '<article class="release-card">'+
  '<div class="meta"><span class="tag">'+(r.prerelease?'ALPHA':'RELEASE')+'</span><small>'+fmtDate(r.published_at)+'</small></div>'+
  '<h3>'+(r.name||r.tag_name)+'</h3><p>'+r.tag_name+'</p><div class="downloads">'+fmt(count)+' downloads</div>'+
  '<div class="asset-list">'+(assets.length?assets.map(a=>'<a href="'+a.browser_download_url+'" target="_blank" rel="noreferrer"><span><b>'+assetLabel(a.name)+'</b><small>'+fmtBytes(a.size)+'</small></span><strong>Baixar</strong></a>').join(''):'<a href="'+r.html_url+'" target="_blank"><span><b>Abrir release</b><small>GitHub</small></span><strong>↗</strong></a>')+'</div></article>'}
function renderArchive(){const filtered=releases.filter(r=>{const k=alphaKey(r.tag_name);if(filter!=='all'&&k!==filter)return false;if(!query)return true;return ((r.tag_name||'')+' '+(r.name||'')).toLowerCase().includes(query)});$('#filteredCount').textContent=filtered.length;$('#totalVersionCount').textContent='de '+releases.length+' versões';const groups={};filtered.forEach(r=>{const k=alphaKey(r.tag_name)||'outros';(groups[k]??=[]).push(r)});const keys=Object.keys(groups).sort((a,b)=>a==='outros'?1:b==='outros'?-1:alphaNum(b)-alphaNum(a));$('#versionArchive').innerHTML=keys.length?keys.map(k=>'<section class="version-group"><div class="version-head"><div><span class="eyebrow">Versões</span><h3>'+(k==='outros'?'Outras versões':'Alpha '+alphaNum(k))+'</h3></div><span>'+groups[k].length+' resultados</span></div><div class="release-grid">'+groups[k].map(releaseCard).join('')+'</div></section>').join(''):'<div class="release-card"><h3>Nenhuma versão encontrada</h3><p>Altere a busca ou o filtro.</p></div>'}
async function loadCatalog(){try{const res=await fetch('site/releases.json',{cache:'no-store'});const c=await res.json();releases=(c.releases||[]).filter(r=>!r.draft);$('#totalDownloads').textContent=fmt(c.total_downloads);const current=releases[0];if(current){$('#currentTag').textContent=current.tag_name;$('#currentName').textContent=current.name||current.tag_name;$('#currentReleaseLink').href=current.html_url;$('#heroVersion').textContent=current.tag_name;$('#trustVersion').textContent=(alphaKey(current.tag_name)||'Alpha').replace('alpha.','Alpha ');const assets=(current.assets||[]).filter(a=>/\.(exe|zip)$/i.test(a.name||''));$('#currentAssets').innerHTML=assets.length?assets.map(assetCard).join(''):'<article class="release-card"><h3>Sem arquivos</h3><p>Abra a release no GitHub.</p></article>';const exe=assets.find(a=>/standalone.*win-x86.*\.exe$/i.test(a.name||''))||assets.find(a=>/\.exe$/i.test(a.name||''));if(exe)$('#heroDownload').href=exe.browser_download_url}
const alphas=[...new Set(releases.map(r=>alphaKey(r.tag_name)).filter(Boolean))].sort((a,b)=>alphaNum(b)-alphaNum(a));$('#alphaFilter').innerHTML='<option value="all">Todas as Alphas</option>'+alphas.map(k=>'<option value="'+k+'">Alpha '+alphaNum(k)+'</option>').join('');$('#newsList').innerHTML=releases.slice(0,4).map((r,i)=>'<article><div class="idx">'+String(i+1).padStart(2,'0')+'</div><div><small>'+r.tag_name+' • '+fmtDate(r.published_at)+'</small><h3>'+(r.name||r.tag_name)+'</h3><p>Build pública do NavBR.</p></div><a href="'+r.html_url+'" target="_blank">↗</a></article>').join('');renderArchive()}catch(e){$('#currentAssets').innerHTML='<article class="release-card"><h3>Catálogo indisponível</h3><p>Use o GitHub Releases.</p></article>'}}
$('#releaseSearch').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();renderArchive()});$('#alphaFilter').addEventListener('change',e=>{filter=e.target.value;renderArchive()});
$('#copyPix').addEventListener('click',async()=>{const key=$('#pixKey').textContent.trim();try{await navigator.clipboard.writeText(key);$('#copyPixStatus').textContent='Chave copiada ✓';setTimeout(()=>$('#copyPixStatus').textContent='Contribuição voluntária',1800)}catch{prompt('Copie a chave Pix:',key)}});
$('#menuButton').addEventListener('click',()=>$('#mobileNav').classList.toggle('open'));$$('#mobileNav a').forEach(a=>a.addEventListener('click',()=>$('#mobileNav').classList.remove('open')));
addEventListener('scroll',()=>{const h=document.documentElement;const p=(h.scrollTop/(h.scrollHeight-h.clientHeight))*100;$('#progress').style.width=Math.max(0,Math.min(100,p))+'%'},{passive:true});
loadCatalog();