using System.Text.Json.Serialization;

namespace NavBR.Client.Multiplayer;

public sealed record MultiplayerSettings(
    string PlayerId,
    string ServerUrl,
    string RoomId,
    string DisplayName,
    string ChatHotkey = "F9",
    string VoiceHotkey = "F10",
    double HudX = 0.02d,
    double HudY = 1.0d,
    double HudZoom = 1.0d,
    double HudMapOpacity = 0.52d,
    int DashboardSettingsVersion = 3,
    bool DashboardEnabled = true,
    double DashboardX = 0.02d,
    double DashboardY = 0.58d,
    double DashboardScale = 0.82d,
    double DashboardOpacity = 0.78d,
    bool DashboardShowFuel = true,
    bool DashboardShowPedals = true,
    bool DashboardShowStatus = true,
    string StopIconStyle = "omsi",
    string? StopCustomIconPath = null,
    bool ExperimentalPhysicalVehiclesEnabled = false,
    bool EnableAutomaticUpnp = false,
    bool EnableApplicationRelay = false,
    string RelayServerUrl = "",
    string VoiceChannel = "general",
    double VoiceProximityMeters = 120d,
    bool VoiceDeafened = false,
    int VoiceInputDeviceNumber = 0,
    int VoiceOutputDeviceNumber = -1,
    string DashboardPreset = "normal",
    string DashboardTheme = "navbr-modern",
    string DashboardAnchor = "free",
    double DashboardWidth = 470d,
    double DashboardHeight = 0d,
    bool DashboardAutoScale = true,
    bool DashboardShowMinimap = true,
    bool DashboardShowMultiplayer = true,
    bool DashboardShowAlerts = true,
    bool DashboardShowSideIndicators = true,
    double DashboardMinimapScale = 1d,
    double DashboardMultiplayerScale = 1d,
    double DashboardAlertsScale = 1d,
    double DashboardSideIndicatorsScale = 1d,
    [property: JsonIgnore] string? EphemeralRoomPassword = null,
    [property: JsonIgnore] bool EphemeralCreatePrivateRoom = false)
{
    public static MultiplayerSettings CreateDefault() => new(
        Guid.NewGuid().ToString("N"),
        "http://127.0.0.1:27730",
        $"navbr-{Random.Shared.Next(1000, 9999)}",
        "Driver",
        "F9",
        "F10",
        0.02d,
        1.0d,
        1.0d,
        0.52d,
        3,
        true,
        0.02d,
        0.58d,
        0.82d,
        0.78d,
        true,
        true,
        true,
        "omsi",
        null,
        false,
        false);
}
