using NavBR.Client.Localization;

namespace NavBR.Client.Windows;

internal static class Alpha12Text
{
    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Catalog =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = Entries(
                ("ShellTagline", "Drive. Navigate. Connect."),
                ("HomeNowTitle", "Your bus right now"),
                ("HomeNowBody", "NavBR keeps technical details in the background and shows first what you need to drive."),
                ("NavigationTitle", "Navigation"),
                ("NavigationBody", "Map, route, stops and trip progress in one place."),
                ("MultiplayerTitle", "Multiplayer"),
                ("MultiplayerBody", "Play with other people without having to understand the technical side of networking."),
                ("HardwareTitle", "Hardware cockpit"),
                ("HardwareBody", "Connect Arduino or ESP32 and bring OMSI information to a physical dashboard."),
                ("FeaturesBody", "All fronts of the next version in a simple view. Experimental features remain protected by opt-in."),
                ("DiagnosticsTitle", "Diagnostics and tools"),
                ("DiagnosticsBody", "Technical area for maintenance, plugin, OMSI profiles, Roadmap Studio and experimental tests."),
                ("CreateRoom", "CREATE A ROOM"),
                ("CreateRoomBody", "You become the host of your own room. NavBR starts the server on your PC and shows the information you need to invite friends."),
                ("CreateRoomStatus", "PEER HOST • TCP 27730"),
                ("JoinRoom", "JOIN A ROOM"),
                ("JoinRoomBody", "Got an invite? Open Multiplayer Central and enter the host details. NavBR handles connection, presence, chat and voice."),
                ("JoinRoomStatus", "INVITE • CHAT • VOICE"),
                ("PublicRooms", "PUBLIC ROOMS"),
                ("PublicRoomsBody", "The public room browser is part of Alpha.12. While it is being developed, the current peer-host mode remains the main path."),
                ("PublicRoomsStatus", "ALPHA.12 • IN DEVELOPMENT"),
                ("MultiplayerCentral", "Multiplayer Central"),
                ("MultiplayerCentralBody", "Room creation/joining, players, chat, voice and connection options are available here."),
                ("OpenMultiplayerCentral", "Open Multiplayer Central"),
                ("MultiplayerTip", "Tip: for your first experience, test between two PCs on the same network before configuring Internet access."),
                ("WelcomeTitle", "Ready for your next trip"),
                ("WelcomeBody", "Open OMSI, choose your bus and let NavBR handle navigation, multiplayer and integrations."),
                ("Ready", "READY"),
                ("FirstSteps", "First steps"),
                ("FirstStepsBody", "1. Open OMSI  •  2. Load a map and bus  •  3. Check that status becomes connected  •  4. Use Navigation or Multiplayer"),
                ("DailyUse", "DAILY USE"),
                ("Home", "⌂  Home"),
                ("NavigationMenu", "⌖  Navigation"),
                ("MultiplayerMenu", "●  Multiplayer"),
                ("HardwareMenu", "▣  Hardware"),
                ("NextVersion", "NEXT VERSION"),
                ("FeaturesMenu", "✦  Alpha.12 features"),
                ("Help", "HELP"),
                ("AdvancedTools", "Advanced tools"),
                ("TechnicalDiagnostics", "◫  Technical diagnostics"),
                ("ShowAdvanced", "Show advanced mode"),
                ("MinimizeTray", "—  Minimize to tray"),
                ("BrandBody", "Simpler outside. More complete inside."),
                ("SettingsButton", "⚙  Settings"),
                ("SettingsTitle", "NavBR settings"),
                ("SettingsSubtitle", "Adjust language, interface and HUD without touching OMSI telemetry."),
                ("Language", "Language"),
                ("HudTheme", "HUD theme"),
                ("AdvancedMode", "Advanced mode"),
                ("AdvancedModeBody", "Shows diagnostics, plugin tools and experimental options in the main menu."),
                ("DrivingTips", "Show driving tips"),
                ("Save", "Save settings"),
                ("Cancel", "Cancel"),
                ("ThemeClassic", "Classic onboard computer"),
                ("ThemeAmber", "Amber LED"),
                ("ThemeLcd", "Modern LCD"),
                ("ThemeMinimal", "Minimal"),
                ("FirstRunTitle", "Welcome to NavBR Alpha.12"),
                ("FirstRunSubtitle", "A quick setup to leave the app ready for your first trip."),
                ("FirstRunStep1", "1. Choose your language"),
                ("FirstRunStep2", "2. Open OMSI normally"),
                ("FirstRunStep2Body", "NavBR detects the running OMSI automatically. You do not need to configure memory addresses or Steam."),
                ("FirstRunStep3", "3. Keep it simple first"),
                ("FirstRunStep3Body", "Use Navigation and test Multiplayer on the same network first. Advanced tools stay hidden until you enable them."),
                ("Continue", "Continue to NavBR"),
                ("DashboardMove", "▦  BUS DASHBOARD • DRAG TO MOVE"),
                ("DashboardSpeed", "SPEED"),
                ("DashboardFuel", "FUEL"),
                ("DashboardThrottle", "THROTTLE"),
                ("DashboardBrake", "BRAKE"),
                ("DashboardDoors", "DOORS"),
                ("DashboardTurn", "TURN"),
                ("DashboardLights", "LIGHTS"),
                ("DashboardWipers", "WIPERS")),
            ["pt"] = Entries(
                ("ShellTagline", "Dirija. Navegue. Conecte."),
                ("HomeNowTitle", "Seu ônibus agora"),
                ("HomeNowBody", "O NavBR deixa os detalhes técnicos em segundo plano e mostra primeiro o que você precisa para dirigir."),
                ("NavigationTitle", "Navegação"),
                ("NavigationBody", "Mapa, rota, paradas e acompanhamento da viagem em um único lugar."),
                ("MultiplayerTitle", "Multiplayer"),
                ("MultiplayerBody", "Jogue com outras pessoas sem precisar entender a parte técnica da rede."),
                ("HardwareTitle", "Hardware cockpit"),
                ("HardwareBody", "Conecte Arduino ou ESP32 e leve informações do OMSI para um painel físico."),
                ("FeaturesBody", "Todas as frentes da próxima versão em uma visão simples. Recursos experimentais continuam protegidos por opt-in."),
                ("DiagnosticsTitle", "Diagnóstico e ferramentas"),
                ("DiagnosticsBody", "Área técnica para manutenção, plugin, perfis OMSI, Roadmap Studio e testes experimentais."),
                ("CreateRoom", "CRIAR UMA SALA"),
                ("CreateRoomBody", "Você vira o host da própria sala. O NavBR inicia o servidor no seu PC e mostra as informações para convidar seus amigos."),
                ("CreateRoomStatus", "PEER-HOST • TCP 27730"),
                ("JoinRoom", "ENTRAR EM UMA SALA"),
                ("JoinRoomBody", "Recebeu um convite? Abra a Central Multiplayer e cole os dados do host. O NavBR cuida da conexão, presença, chat e voz."),
                ("JoinRoomStatus", "CONVITE • CHAT • VOZ"),
                ("PublicRooms", "SALAS PÚBLICAS"),
                ("PublicRoomsBody", "O navegador de salas públicas faz parte da Alpha.12. Enquanto ele é desenvolvido, o modo peer-host atual continua sendo o caminho principal."),
                ("PublicRoomsStatus", "ALPHA.12 • EM DESENVOLVIMENTO"),
                ("MultiplayerCentral", "Central Multiplayer"),
                ("MultiplayerCentralBody", "Aqui ficam criação/entrada de sala, jogadores, chat, voz e opções de conexão."),
                ("OpenMultiplayerCentral", "Abrir Central Multiplayer"),
                ("MultiplayerTip", "Dica: para uma primeira experiência, teste entre dois PCs na mesma rede antes de configurar acesso pela Internet."),
                ("WelcomeTitle", "Tudo pronto para sua próxima viagem"),
                ("WelcomeBody", "Abra o OMSI, escolha seu ônibus e deixe o NavBR cuidar de navegação, multiplayer e integrações."),
                ("Ready", "PRONTO"),
                ("FirstSteps", "Primeiros passos"),
                ("FirstStepsBody", "1. Abra o OMSI  •  2. Carregue mapa e ônibus  •  3. Confira se o status fica conectado  •  4. Use Navegação ou Multiplayer"),
                ("DailyUse", "USO DIÁRIO"),
                ("Home", "⌂  Início"),
                ("NavigationMenu", "⌖  Navegação"),
                ("MultiplayerMenu", "●  Multiplayer"),
                ("HardwareMenu", "▣  Hardware"),
                ("NextVersion", "PRÓXIMA VERSÃO"),
                ("FeaturesMenu", "✦  Recursos Alpha.12"),
                ("Help", "AJUDA"),
                ("AdvancedTools", "Ferramentas avançadas"),
                ("TechnicalDiagnostics", "◫  Diagnóstico técnico"),
                ("ShowAdvanced", "Mostrar modo avançado"),
                ("MinimizeTray", "—  Minimizar para bandeja"),
                ("BrandBody", "Mais simples por fora. Mais completo por dentro."),
                ("SettingsButton", "⚙  Configurações"),
                ("SettingsTitle", "Configurações do NavBR"),
                ("SettingsSubtitle", "Ajuste idioma, interface e HUD sem mexer na telemetria do OMSI."),
                ("Language", "Idioma"),
                ("HudTheme", "Tema do HUD"),
                ("AdvancedMode", "Modo avançado"),
                ("AdvancedModeBody", "Mostra diagnóstico, ferramentas do plugin e opções experimentais no menu principal."),
                ("DrivingTips", "Mostrar dicas de condução"),
                ("Save", "Salvar configurações"),
                ("Cancel", "Cancelar"),
                ("ThemeClassic", "Computador de bordo clássico"),
                ("ThemeAmber", "LED âmbar"),
                ("ThemeLcd", "LCD moderno"),
                ("ThemeMinimal", "Minimalista"),
                ("FirstRunTitle", "Bem-vindo ao NavBR Alpha.12"),
                ("FirstRunSubtitle", "Uma configuração rápida para deixar o aplicativo pronto para sua primeira viagem."),
                ("FirstRunStep1", "1. Escolha seu idioma"),
                ("FirstRunStep2", "2. Abra o OMSI normalmente"),
                ("FirstRunStep2Body", "O NavBR detecta o OMSI em execução automaticamente. Você não precisa configurar endereços de memória nem a Steam."),
                ("FirstRunStep3", "3. Comece de forma simples"),
                ("FirstRunStep3Body", "Use Navegação e teste o Multiplayer primeiro na mesma rede. As ferramentas avançadas ficam escondidas até você ativá-las."),
                ("Continue", "Continuar para o NavBR"),
                ("DashboardMove", "▦  PAINEL DO ÔNIBUS • ARRASTE PARA MOVER"),
                ("DashboardSpeed", "VELOCIDADE"),
                ("DashboardFuel", "COMBUSTÍVEL"),
                ("DashboardThrottle", "ACEL"),
                ("DashboardBrake", "FREIO"),
                ("DashboardDoors", "PORTAS"),
                ("DashboardTurn", "SETA"),
                ("DashboardLights", "LUZ"),
                ("DashboardWipers", "LIMP")),
            ["es"] = Entries(
                ("ShellTagline", "Conduce. Navega. Conecta."),
                ("HomeNowTitle", "Tu autobús ahora"),
                ("HomeNowBody", "NavBR deja los detalles técnicos en segundo plano y muestra primero lo que necesitas para conducir."),
                ("NavigationTitle", "Navegación"),
                ("NavigationBody", "Mapa, ruta, paradas y seguimiento del viaje en un solo lugar."),
                ("MultiplayerTitle", "Multijugador"),
                ("MultiplayerBody", "Juega con otras personas sin tener que entender la parte técnica de la red."),
                ("HardwareTitle", "Cabina de hardware"),
                ("HardwareBody", "Conecta Arduino o ESP32 y lleva la información de OMSI a un panel físico."),
                ("FeaturesBody", "Todas las áreas de la próxima versión en una vista sencilla. Las funciones experimentales siguen protegidas por activación explícita."),
                ("DiagnosticsTitle", "Diagnóstico y herramientas"),
                ("DiagnosticsBody", "Área técnica para mantenimiento, plugin, perfiles OMSI, Roadmap Studio y pruebas experimentales."),
                ("CreateRoom", "CREAR UNA SALA"),
                ("CreateRoomBody", "Tu PC se convierte en el host de la sala. NavBR inicia el servidor y muestra la información para invitar a tus amigos."),
                ("CreateRoomStatus", "PEER-HOST • TCP 27730"),
                ("JoinRoom", "ENTRAR EN UNA SALA"),
                ("JoinRoomBody", "¿Recibiste una invitación? Abre la Central Multijugador e introduce los datos del host. NavBR gestiona conexión, presencia, chat y voz."),
                ("JoinRoomStatus", "INVITACIÓN • CHAT • VOZ"),
                ("PublicRooms", "SALAS PÚBLICAS"),
                ("PublicRoomsBody", "El navegador de salas públicas forma parte de Alpha.12. Mientras se desarrolla, el modo peer-host actual sigue siendo la opción principal."),
                ("PublicRoomsStatus", "ALPHA.12 • EN DESARROLLO"),
                ("MultiplayerCentral", "Central Multijugador"),
                ("MultiplayerCentralBody", "Aquí están la creación/entrada de salas, jugadores, chat, voz y opciones de conexión."),
                ("OpenMultiplayerCentral", "Abrir Central Multijugador"),
                ("MultiplayerTip", "Consejo: para la primera prueba, usa dos PCs en la misma red antes de configurar el acceso por Internet."),
                ("WelcomeTitle", "Todo listo para tu próximo viaje"),
                ("WelcomeBody", "Abre OMSI, elige tu autobús y deja que NavBR se encargue de navegación, multijugador e integraciones."),
                ("Ready", "LISTO"),
                ("FirstSteps", "Primeros pasos"),
                ("FirstStepsBody", "1. Abre OMSI  •  2. Carga mapa y autobús  •  3. Comprueba que el estado esté conectado  •  4. Usa Navegación o Multijugador"),
                ("DailyUse", "USO DIARIO"),
                ("Home", "⌂  Inicio"),
                ("NavigationMenu", "⌖  Navegación"),
                ("MultiplayerMenu", "●  Multijugador"),
                ("HardwareMenu", "▣  Hardware"),
                ("NextVersion", "PRÓXIMA VERSIÓN"),
                ("FeaturesMenu", "✦  Funciones Alpha.12"),
                ("Help", "AYUDA"),
                ("AdvancedTools", "Herramientas avanzadas"),
                ("TechnicalDiagnostics", "◫  Diagnóstico técnico"),
                ("ShowAdvanced", "Mostrar modo avanzado"),
                ("MinimizeTray", "—  Minimizar a la bandeja"),
                ("BrandBody", "Más simple por fuera. Más completo por dentro."),
                ("SettingsButton", "⚙  Configuración"),
                ("SettingsTitle", "Configuración de NavBR"),
                ("SettingsSubtitle", "Ajusta idioma, interfaz y HUD sin tocar la telemetría de OMSI."),
                ("Language", "Idioma"),
                ("HudTheme", "Tema del HUD"),
                ("AdvancedMode", "Modo avanzado"),
                ("AdvancedModeBody", "Muestra diagnóstico, herramientas del plugin y opciones experimentales en el menú principal."),
                ("DrivingTips", "Mostrar consejos de conducción"),
                ("Save", "Guardar configuración"),
                ("Cancel", "Cancelar"),
                ("ThemeClassic", "Ordenador de a bordo clásico"),
                ("ThemeAmber", "LED ámbar"),
                ("ThemeLcd", "LCD moderno"),
                ("ThemeMinimal", "Minimalista"),
                ("FirstRunTitle", "Bienvenido a NavBR Alpha.12"),
                ("FirstRunSubtitle", "Una configuración rápida para dejar la aplicación lista para tu primer viaje."),
                ("FirstRunStep1", "1. Elige tu idioma"),
                ("FirstRunStep2", "2. Abre OMSI normalmente"),
                ("FirstRunStep2Body", "NavBR detecta automáticamente OMSI en ejecución. No necesitas configurar direcciones de memoria ni Steam."),
                ("FirstRunStep3", "3. Empieza de forma sencilla"),
                ("FirstRunStep3Body", "Usa Navegación y prueba primero Multijugador en la misma red. Las herramientas avanzadas permanecen ocultas hasta que las actives."),
                ("Continue", "Continuar a NavBR"),
                ("DashboardMove", "▦  PANEL DEL AUTOBÚS • ARRASTRA PARA MOVER"),
                ("DashboardSpeed", "VELOCIDAD"),
                ("DashboardFuel", "COMBUSTIBLE"),
                ("DashboardThrottle", "ACEL"),
                ("DashboardBrake", "FRENO"),
                ("DashboardDoors", "PUERTAS"),
                ("DashboardTurn", "GIRO"),
                ("DashboardLights", "LUCES"),
                ("DashboardWipers", "LIMPIA")),
            ["de"] = Entries(
                ("ShellTagline", "Fahren. Navigieren. Verbinden."),
                ("HomeNowTitle", "Dein Bus jetzt"),
                ("HomeNowBody", "NavBR hält technische Details im Hintergrund und zeigt zuerst, was du zum Fahren brauchst."),
                ("NavigationTitle", "Navigation"),
                ("NavigationBody", "Karte, Route, Haltestellen und Fahrtverlauf an einem Ort."),
                ("MultiplayerTitle", "Mehrspieler"),
                ("MultiplayerBody", "Spiele mit anderen, ohne die technischen Netzwerkdetails verstehen zu müssen."),
                ("HardwareTitle", "Hardware-Cockpit"),
                ("HardwareBody", "Verbinde Arduino oder ESP32 und bringe OMSI-Daten auf ein physisches Dashboard."),
                ("FeaturesBody", "Alle Bereiche der nächsten Version in einer einfachen Ansicht. Experimentelle Funktionen bleiben durch Opt-in geschützt."),
                ("DiagnosticsTitle", "Diagnose und Werkzeuge"),
                ("DiagnosticsBody", "Technischer Bereich für Wartung, Plugin, OMSI-Profile, Roadmap Studio und experimentelle Tests."),
                ("CreateRoom", "RAUM ERSTELLEN"),
                ("CreateRoomBody", "Dein PC wird zum Host des Raums. NavBR startet den Server und zeigt die Daten zum Einladen deiner Freunde."),
                ("CreateRoomStatus", "PEER-HOST • TCP 27730"),
                ("JoinRoom", "RAUM BEITRETEN"),
                ("JoinRoomBody", "Einladung erhalten? Öffne die Mehrspieler-Zentrale und gib die Host-Daten ein. NavBR übernimmt Verbindung, Präsenz, Chat und Sprache."),
                ("JoinRoomStatus", "EINLADUNG • CHAT • SPRACHE"),
                ("PublicRooms", "ÖFFENTLICHE RÄUME"),
                ("PublicRoomsBody", "Der Browser für öffentliche Räume ist Teil von Alpha.12. Bis dahin bleibt der aktuelle Peer-Host-Modus der Hauptweg."),
                ("PublicRoomsStatus", "ALPHA.12 • IN ENTWICKLUNG"),
                ("MultiplayerCentral", "Mehrspieler-Zentrale"),
                ("MultiplayerCentralBody", "Hier findest du Raum erstellen/beitreten, Spieler, Chat, Sprache und Verbindungsoptionen."),
                ("OpenMultiplayerCentral", "Mehrspieler-Zentrale öffnen"),
                ("MultiplayerTip", "Tipp: Teste zuerst mit zwei PCs im selben Netzwerk, bevor du den Internetzugang einrichtest."),
                ("WelcomeTitle", "Bereit für deine nächste Fahrt"),
                ("WelcomeBody", "Starte OMSI, wähle deinen Bus und lass NavBR Navigation, Mehrspieler und Integrationen übernehmen."),
                ("Ready", "BEREIT"),
                ("FirstSteps", "Erste Schritte"),
                ("FirstStepsBody", "1. OMSI starten  •  2. Karte und Bus laden  •  3. Verbundenen Status prüfen  •  4. Navigation oder Mehrspieler nutzen"),
                ("DailyUse", "TÄGLICHE NUTZUNG"),
                ("Home", "⌂  Start"),
                ("NavigationMenu", "⌖  Navigation"),
                ("MultiplayerMenu", "●  Mehrspieler"),
                ("HardwareMenu", "▣  Hardware"),
                ("NextVersion", "NÄCHSTE VERSION"),
                ("FeaturesMenu", "✦  Alpha.12-Funktionen"),
                ("Help", "HILFE"),
                ("AdvancedTools", "Erweiterte Werkzeuge"),
                ("TechnicalDiagnostics", "◫  Technische Diagnose"),
                ("ShowAdvanced", "Erweiterten Modus anzeigen"),
                ("MinimizeTray", "—  In Infobereich minimieren"),
                ("BrandBody", "Außen einfacher. Innen vollständiger."),
                ("SettingsButton", "⚙  Einstellungen"),
                ("SettingsTitle", "NavBR-Einstellungen"),
                ("SettingsSubtitle", "Sprache, Oberfläche und HUD anpassen, ohne OMSI-Telemetrie zu verändern."),
                ("Language", "Sprache"),
                ("HudTheme", "HUD-Design"),
                ("AdvancedMode", "Erweiterter Modus"),
                ("AdvancedModeBody", "Zeigt Diagnose, Plugin-Werkzeuge und experimentelle Optionen im Hauptmenü."),
                ("DrivingTips", "Fahrhinweise anzeigen"),
                ("Save", "Einstellungen speichern"),
                ("Cancel", "Abbrechen"),
                ("ThemeClassic", "Klassischer Bordcomputer"),
                ("ThemeAmber", "Bernstein-LED"),
                ("ThemeLcd", "Modernes LCD"),
                ("ThemeMinimal", "Minimal"),
                ("FirstRunTitle", "Willkommen bei NavBR Alpha.12"),
                ("FirstRunSubtitle", "Eine kurze Einrichtung für deine erste Fahrt."),
                ("FirstRunStep1", "1. Sprache wählen"),
                ("FirstRunStep2", "2. OMSI normal starten"),
                ("FirstRunStep2Body", "NavBR erkennt das laufende OMSI automatisch. Speicheradressen oder Steam müssen nicht konfiguriert werden."),
                ("FirstRunStep3", "3. Zuerst einfach starten"),
                ("FirstRunStep3Body", "Nutze Navigation und teste Mehrspieler zuerst im selben Netzwerk. Erweiterte Werkzeuge bleiben verborgen, bis du sie aktivierst."),
                ("Continue", "Weiter zu NavBR"),
                ("DashboardMove", "▦  BUS-DASHBOARD • ZUM VERSCHIEBEN ZIEHEN"),
                ("DashboardSpeed", "GESCHWINDIGKEIT"),
                ("DashboardFuel", "KRAFTSTOFF"),
                ("DashboardThrottle", "GAS"),
                ("DashboardBrake", "BREMSE"),
                ("DashboardDoors", "TÜREN"),
                ("DashboardTurn", "BLINKER"),
                ("DashboardLights", "LICHT"),
                ("DashboardWipers", "WISCHER")),
            ["fr"] = Entries(
                ("ShellTagline", "Conduisez. Naviguez. Connectez."),
                ("HomeNowTitle", "Votre bus maintenant"),
                ("HomeNowBody", "NavBR garde les détails techniques en arrière-plan et montre d’abord ce dont vous avez besoin pour conduire."),
                ("NavigationTitle", "Navigation"),
                ("NavigationBody", "Carte, itinéraire, arrêts et suivi du trajet au même endroit."),
                ("MultiplayerTitle", "Multijoueur"),
                ("MultiplayerBody", "Jouez avec d’autres personnes sans devoir comprendre la partie technique du réseau."),
                ("HardwareTitle", "Cockpit matériel"),
                ("HardwareBody", "Connectez Arduino ou ESP32 et affichez les informations OMSI sur un tableau de bord physique."),
                ("FeaturesBody", "Tous les axes de la prochaine version dans une vue simple. Les fonctions expérimentales restent protégées par une activation explicite."),
                ("DiagnosticsTitle", "Diagnostic et outils"),
                ("DiagnosticsBody", "Zone technique pour maintenance, plugin, profils OMSI, Roadmap Studio et tests expérimentaux."),
                ("CreateRoom", "CRÉER UN SALON"),
                ("CreateRoomBody", "Votre PC devient l’hôte du salon. NavBR démarre le serveur et affiche les informations pour inviter vos amis."),
                ("CreateRoomStatus", "PEER-HOST • TCP 27730"),
                ("JoinRoom", "REJOINDRE UN SALON"),
                ("JoinRoomBody", "Vous avez reçu une invitation ? Ouvrez la Centrale Multijoueur et saisissez les données de l’hôte. NavBR gère connexion, présence, chat et voix."),
                ("JoinRoomStatus", "INVITATION • CHAT • VOIX"),
                ("PublicRooms", "SALONS PUBLICS"),
                ("PublicRoomsBody", "Le navigateur de salons publics fait partie d’Alpha.12. Pendant son développement, le mode peer-host actuel reste la voie principale."),
                ("PublicRoomsStatus", "ALPHA.12 • EN DÉVELOPPEMENT"),
                ("MultiplayerCentral", "Centrale Multijoueur"),
                ("MultiplayerCentralBody", "Création/rejoindre un salon, joueurs, chat, voix et options de connexion sont regroupés ici."),
                ("OpenMultiplayerCentral", "Ouvrir la Centrale Multijoueur"),
                ("MultiplayerTip", "Conseil : pour un premier essai, utilisez deux PC sur le même réseau avant de configurer l’accès Internet."),
                ("WelcomeTitle", "Prêt pour votre prochain trajet"),
                ("WelcomeBody", "Ouvrez OMSI, choisissez votre bus et laissez NavBR gérer navigation, multijoueur et intégrations."),
                ("Ready", "PRÊT"),
                ("FirstSteps", "Premiers pas"),
                ("FirstStepsBody", "1. Ouvrez OMSI  •  2. Chargez carte et bus  •  3. Vérifiez l’état connecté  •  4. Utilisez Navigation ou Multijoueur"),
                ("DailyUse", "USAGE QUOTIDIEN"),
                ("Home", "⌂  Accueil"),
                ("NavigationMenu", "⌖  Navigation"),
                ("MultiplayerMenu", "●  Multijoueur"),
                ("HardwareMenu", "▣  Matériel"),
                ("NextVersion", "PROCHAINE VERSION"),
                ("FeaturesMenu", "✦  Fonctions Alpha.12"),
                ("Help", "AIDE"),
                ("AdvancedTools", "Outils avancés"),
                ("TechnicalDiagnostics", "◫  Diagnostic technique"),
                ("ShowAdvanced", "Afficher le mode avancé"),
                ("MinimizeTray", "—  Réduire dans la zone de notification"),
                ("BrandBody", "Plus simple à l’extérieur. Plus complet à l’intérieur."),
                ("SettingsButton", "⚙  Paramètres"),
                ("SettingsTitle", "Paramètres NavBR"),
                ("SettingsSubtitle", "Réglez la langue, l’interface et le HUD sans toucher à la télémétrie OMSI."),
                ("Language", "Langue"),
                ("HudTheme", "Thème du HUD"),
                ("AdvancedMode", "Mode avancé"),
                ("AdvancedModeBody", "Affiche diagnostic, outils du plugin et options expérimentales dans le menu principal."),
                ("DrivingTips", "Afficher les conseils de conduite"),
                ("Save", "Enregistrer les paramètres"),
                ("Cancel", "Annuler"),
                ("ThemeClassic", "Ordinateur de bord classique"),
                ("ThemeAmber", "LED ambre"),
                ("ThemeLcd", "LCD moderne"),
                ("ThemeMinimal", "Minimaliste"),
                ("FirstRunTitle", "Bienvenue dans NavBR Alpha.12"),
                ("FirstRunSubtitle", "Une configuration rapide pour préparer l’application à votre premier trajet."),
                ("FirstRunStep1", "1. Choisissez votre langue"),
                ("FirstRunStep2", "2. Ouvrez OMSI normalement"),
                ("FirstRunStep2Body", "NavBR détecte automatiquement OMSI en cours d’exécution. Vous n’avez pas à configurer d’adresses mémoire ni Steam."),
                ("FirstRunStep3", "3. Commencez simplement"),
                ("FirstRunStep3Body", "Utilisez Navigation et testez d’abord le Multijoueur sur le même réseau. Les outils avancés restent masqués jusqu’à leur activation."),
                ("Continue", "Continuer vers NavBR"),
                ("DashboardMove", "▦  TABLEAU DU BUS • FAITES GLISSER POUR DÉPLACER"),
                ("DashboardSpeed", "VITESSE"),
                ("DashboardFuel", "CARBURANT"),
                ("DashboardThrottle", "ACCÉL"),
                ("DashboardBrake", "FREIN"),
                ("DashboardDoors", "PORTES"),
                ("DashboardTurn", "CLIGNO"),
                ("DashboardLights", "FEUX"),
                ("DashboardWipers", "ESSUIE"))
        };

    public static string Get(string key)
    {
        var language = LocalizationService.CurrentCulture.TwoLetterISOLanguageName;
        if (Catalog.TryGetValue(language, out var localized) && localized.TryGetValue(key, out var value))
        {
            return value;
        }

        return Catalog["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static bool TryResolveKey(string text, out string key)
    {
        foreach (var localized in Catalog.Values)
        {
            foreach (var pair in localized)
            {
                if (string.Equals(pair.Value, text, StringComparison.Ordinal))
                {
                    key = pair.Key;
                    return true;
                }
            }
        }

        key = string.Empty;
        return false;
    }

    public static string ThemeDisplayName(string theme) => theme switch
    {
        "amber" => Get("ThemeAmber"),
        "lcd" => Get("ThemeLcd"),
        "minimal" => Get("ThemeMinimal"),
        _ => Get("ThemeClassic")
    };

    public static IReadOnlyList<string> ThemeIds { get; } = ["classic", "amber", "lcd", "minimal"];

    private static IReadOnlyDictionary<string, string> Entries(params (string Key, string Value)[] values) =>
        values.ToDictionary(item => item.Key, item => item.Value, StringComparer.OrdinalIgnoreCase);
}
